files:
  - index.tpl.html
  - about.tpl.html
  - moar.tpl.html

variables:
  base_url: '//localhost:1234'
  twitter_url: 'https://www.twitter.com/johnmurray_io'
  github_repo_url: 'https://github.com/Johnmurray/cpp-vs'

production:
  variables:
    base_url: '//cpp-vs.com'