files:
  - index.tpl.html
  - about.tpl.html
  - moar.tpl.html

versus_file:   'versus.tpl.html'
versus_folder: 'versus'
versus:
  - name:   'NodeJS'
    folder: 'node-js'
  - name:   'Ruby'
    folder: 'ruby'
  - name:   'Go'
    folder: 'go'
  - name:   'Scala'
    folder: 'scala'

variables:
  base_url: '//localhost:1234'
  twitter_url: 'https://www.twitter.com/johnmurray_io'
  github_repo_url: 'https://github.com/Johnmurray/cpp-vs'

production:
  variables:
    base_url: '//cpp-vs.com'